[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd packages/nextjs && yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"